apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/frontend.yaml
  - manifests/ingress.yaml
  - manifests/budget.yaml
  - manifests/autoscaler.yaml
images:
  - name: PROJECT/FRONTEND_IMAGE
    newName: 1701002/todos-frontend:v1.03
  - name: PROJECT/IMAGE_FINDER
    newName: 1701002/image-finder:v1.03